version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev-deps:
        dependency-type: development
      patch-updates:
        update-types: ["patch"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      patch-updates:
        update-types: ["patch"]
